on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
name:
jobs:
  build:
    name: Build and release
    runs-on:  macos latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.0'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug"
          release_notes_file: "release_notes.md"
          github_token: ${{ secrets.TOKEN }}
          