name: Flutter Build & Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up local.properties
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > duman_app/android/local.properties  # Set SDK path

      - name: Install Snyk
        run: npm install -g snyk  # Install the Snyk CLI globally

      - name: Run Snyk with Debug
        working-directory: duman_app/android
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_DEBUG: '1'  # Enable debug mode for detailed logs

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up local.properties
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > duman_app/android/local.properties  # Set SDK path

      - name: Build APK
        working-directory: duman_app
        run: |
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: duman_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
