name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: |
          flutter pub get
          cd android
          ./gradlew dependencies
        working-directory: duman_app

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          DEBUG: '*snyk*'
        with:
          command: monitor
          args: --gradle-sub-project=app --configuration-matching='^(api|implementation|compile).*$'
          json: true
        working-directory: duman_app/android

      - name: Snyk Test with Debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          DEBUG: '*snyk*'
        run: |
          cd duman_app/android
          snyk test \
            --gradle-sub-project=app \
            --configuration-matching='^(api|implementation|compile).*$' \
            --debug || true

      # Generate and export Snyk report
      - name: Generate Snyk Report
        if: always()
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd duman_app/android
          snyk test \
            --gradle-sub-project=app \
            --configuration-matching='^(api|implementation|compile).*$' \
            --json > snyk-report.json || true

      # Upload Snyk report as artifact
      - name: Upload Snyk Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: duman_app/android/snyk-report.json
          retention-days: 7

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: security
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable Analytics
        run: flutter config --no-analytics

      - name: Get dependencies
        run: flutter pub get
        working-directory: duman_app

      - name: Analyze code
        run: flutter analyze
        working-directory: duman_app

      - name: Format check
        run: dart format --set-exit-if-changed .
        working-directory: duman_app

      - name: Run tests
        run: flutter test
        working-directory: duman_app

      - name: Build APK
        run: flutter build apk --release
        working-directory: duman_app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: duman_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 7