name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        working-directory: duman_app
        run: flutter pub get

      # Setup Gradle
      - name: Grant execute permission for gradlew
        working-directory: duman_app/android
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper
          fi
          chmod +x ./gradlew

      - name: Run Gradle dependencies
        working-directory: duman_app/android
        run: ./gradlew dependencies

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          DEBUG: '*snyk*'
        with:
          args: --gradle-sub-project=app --configuration-matching='^(api|implementation|compile).*$'
          project-path: ./duman_app/android

      - name: Snyk Test with Debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          DEBUG: '*snyk*'
        working-directory: duman_app/android
        run: |
          snyk test \
            --gradle-sub-project=app \
            --configuration-matching='^(api|implementation|compile).*$' \
            --debug || true

      - name: Generate Snyk Report
        if: always()
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: duman_app/android
        run: |
          snyk test \
            --gradle-sub-project=app \
            --configuration-matching='^(api|implementation|compile).*$' \
            --json > snyk-report.json || true

      - name: Upload Snyk Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: duman_app/android/snyk-report.json
          retention-days: 7

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: security
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable Analytics
        run: flutter config --no-analytics

      - name: Get dependencies
        working-directory: duman_app
        run: flutter pub get

      # Setup Gradle for build job
      - name: Grant execute permission for gradlew
        working-directory: duman_app/android
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper
          fi
          chmod +x ./gradlew

      - name: Analyze code
        working-directory: duman_app
        run: flutter analyze

      - name: Format check
        working-directory: duman_app
        run: dart format --set-exit-if-changed .

      - name: Run tests
        working-directory: duman_app
        run: flutter test

      - name: Build APK
        working-directory: duman_app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: duman_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 7