name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use your SSH private key here

      - name: Set up Git credentials
        run: |
          git config --global user.name "lbx18"  # Update with your name
          git config --global user.email "jojolucky221@gmail.com"  # Update with your email
          echo "${{ secrets.GITHUB_TOKEN }}" | git credential approve

      - name: Run Snyk for Security Scanning
        uses: snyk/actions/setup@latest
        with:
          token: ${{ env.SNYK_TOKEN }}

      - name: Snyk Monitor Dependencies
        run: snyk monitor --all-projects

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use your SSH private key here

      # Set up Java 17 for Android Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Disable Analytics
        run: flutter config --no-analytics

      - name: Get dependencies
        run: flutter pub get
        working-directory: duman_app

      - name: Run tests
        run: flutter test
        working-directory: duman_app

      - name: Build APK
        run: flutter build apk --release
        working-directory: duman_app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: duman_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
