name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get
        working-directory: duman_app

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@master

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Package Vulnerabilities Test
        continue-on-error: true
        run: |
          cd duman_app
          snyk test --file=pubspec.yaml --package-manager=dart --severity-threshold=high

      - name: Monitor Project in Snyk
        continue-on-error: true
        run: |
          cd duman_app
          snyk monitor --file=pubspec.yaml --package-manager=dart

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: security
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable Analytics
        run: flutter config --no-analytics

      - name: Get dependencies
        run: flutter pub get
        working-directory: duman_app

      - name: Analyze code
        run: flutter analyze
        working-directory: duman_app

      - name: Format check
        run: dart format --set-exit-if-changed .
        working-directory: duman_app

      - name: Run tests
        run: flutter test
        working-directory: duman_app

      - name: Build APK
        run: flutter build apk --release
        working-directory: duman_app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: duman_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 7